### ISSUE TITLE
Can't get correct result on Android Mobile phone.

### ISSUE THREAD

**Issue by omega4727** [keijiro/Isaura#1] opened 2018-10-24 06:03 UTC
I build a apk on Unity 2018.2，and it can run.
But the aura effect disappeared.

**Comment by keijiro** [comment] 2019-04-05 02:04
Unfortunately, I can't reproduce the issue on my side.

I'm closing this issue. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2019-04-05 02:04 UTC
Labels: question
